EACH_CARD_SIZE = 12 + 4
CARD_SIZE = 16 * EACH_CARD_SIZE

EACH_PLAYER_SIZE = 16
PLAYER_SIZE = 3 * EACH_PLAYER_SIZE

CURRENT_HAND_SIZE = 4 + 11 + 4 + 8

CARDS_PLAYED_SIZE = 3 + 6

NN_INPUT_SIZE = CARD_SIZE + PLAYER_SIZE + CURRENT_HAND_SIZE + CARDS_PLAYED_SIZE
